name: "BoneBox"
version: "0.0.1"
main: com.bonesnetwork.bonebox.minecraft.BoneBoxPlugin
api-version: '1.20'

dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    KoreChat:
      load: BEFORE
      required: true
      join-classpath: true